apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: wishlist-app
    spec:
      containers:
        - name: wishlist-app-container
          image: rakesh8874/myappimg5:latest
          ports:
          - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_USER
              value: hello_flask
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: hello_flask_db
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

  selector:
    matchLabels:
      component: wishlist-app