apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment

spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: wishlist-app
    spec:
      containers:
        - name: wishlist-app-container
          image: rakesh8874/myappimg7:latest
          ports:
          - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: basic_crud_db

            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PGPASSWORD
  selector:
    matchLabels:
      component: wishlist-app