apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-crud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basiccrudapp
  template:
    metadata:
      labels:
        app: basiccrudapp
    spec:
      containers:
      - name: basiccrudapp
        image: rakesh8874/basiccrud:latest
        ports:
        - containerPort: 8000
        env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: basic_crud_db

            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PGPASSWORD
