apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
data:
  POSTGRES_HOST: "django-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "root"
  POSTGRES_DB: "mydb"